<#
.SYNOPSIS
    In-sandbox installation orchestrator. Runs automatically on sandbox startup via autostart.cmd.

.DESCRIPTION
    Reads the install-manifest.json generated by Start-Sandbox.ps1 on the host, then installs
    all selected tools in dependency order. Logs all output to %USERPROFILE%\Desktop\install-log.txt.

    This script is NOT intended to be run manually on the host. It runs inside Windows Sandbox only.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'   # Log failures and continue to next tool rather than hard-stop

# -- Paths --------------------------------------------------------------------

$sandboxScripts = 'C:\Users\WDAGUtilityAccount\Desktop\scripts'
$setupDir       = Join-Path $sandboxScripts 'setups'
$manifestPath   = Join-Path $sandboxScripts 'install-manifest.json'
$logPath        = 'C:\Users\WDAGUtilityAccount\Desktop\install-log.txt'
$tempDir        = $env:TEMP
$sevenZip       = "$env:PROGRAMFILES\7-Zip\7z.exe"

# -- Logging -------------------------------------------------------------------

function Write-InstallLog {
    param([string]$Message, [string]$Level = 'INFO')
    $entry = '[{0}] [{1}] {2}' -f (Get-Date -Format 'HH:mm:ss'), $Level, $Message
    Add-Content -Path $logPath -Value $entry
    $color = switch ($Level) {
        'OK'    { [ConsoleColor]::Green }
        'WARN'  { [ConsoleColor]::Yellow }
        'FAIL'  { [ConsoleColor]::Red }
        default { [ConsoleColor]::White }
    }
    $Host.UI.WriteLine($color, $Host.UI.RawUI.BackgroundColor, $entry)
}

# -- Copy setups to writable temp ----------------------------------------------
# The mapped scripts folder is read-only. MSI and some installers require files
# to be on a writable path; copy everything to %TEMP% once.

function Copy-SetupsToTemp {
    Write-InstallLog 'Copying installers to temp...'
    # Exclude dotfiles (.gitkeep etc.) -- only copy real installer files
    $files = Get-ChildItem -Path $setupDir -File -ErrorAction Stop |
             Where-Object { $_.Name -notlike '.*' }
    if ($files.Count -eq 0) {
        throw "No installer files found in $setupDir. Was Start-Sandbox.ps1 run on the host first?"
    }
    foreach ($f in $files) {
        $dest = Join-Path $tempDir $f.Name
        if (-not (Test-Path $dest)) {
            Copy-Item -Path $f.FullName -Destination $dest -Force -ErrorAction Stop
        }
    }
    Write-InstallLog "Copied $($files.Count) file(s) to $tempDir" -Level 'OK'
}

# -- Install helpers -----------------------------------------------------------

function Invoke-Installer {
    param(
        [string]$FilePath,
        [string]$InstallArgs = '',
        [string]$Name
    )
    Write-InstallLog "Installing: $Name"
    if (-not (Test-Path $FilePath)) {
        Write-InstallLog "  Installer not found: $FilePath" -Level 'FAIL'
        return $false
    }
    try {
        if ($FilePath -match '\.msi$') {
            $proc = Start-Process 'msiexec.exe' -ArgumentList "/i `"$FilePath`" $InstallArgs" -Wait -PassThru
        } else {
            $proc = Start-Process $FilePath -ArgumentList $InstallArgs -Wait -PassThru
        }
        # Exit code 3010 = success, reboot required (expected in sandbox context)
        if ($proc.ExitCode -eq 0 -or $proc.ExitCode -eq 3010) {
            Write-InstallLog "  $Name -- OK (exit $($proc.ExitCode))" -Level 'OK'
            return $true
        } else {
            Write-InstallLog "  $Name -- exit code $($proc.ExitCode)" -Level 'WARN'
            return $false
        }
    } catch {
        Write-InstallLog "  $Name -- exception: $_" -Level 'FAIL'
        return $false
    }
}

function Expand-ZipTool {
    param(
        [string]$ZipPath,
        [string]$Destination,
        [string]$Name
    )
    Write-InstallLog "Extracting: $Name"
    if (-not (Test-Path $ZipPath)) {
        Write-InstallLog "  Archive not found: $ZipPath" -Level 'FAIL'
        return $false
    }
    if (-not (Test-Path $sevenZip)) {
        Write-InstallLog "  7-Zip not found at $sevenZip -- was it installed first?" -Level 'FAIL'
        return $false
    }
    $resolvedDest = [System.Environment]::ExpandEnvironmentVariables($Destination)
    try {
        $proc = Start-Process $sevenZip -ArgumentList "x `"$ZipPath`" -o`"$resolvedDest`" -y" -Wait -PassThru
        if ($proc.ExitCode -eq 0) {
            Write-InstallLog "  $Name -- extracted to $resolvedDest" -Level 'OK'
            return $true
        } else {
            Write-InstallLog "  $Name -- 7z exit code $($proc.ExitCode)" -Level 'WARN'
            return $false
        }
    } catch {
        Write-InstallLog "  $Name -- extraction exception: $_" -Level 'FAIL'
        return $false
    }
}

function Install-ZipThenExe {
    param(
        [string]$ZipPath,
        [string]$InnerExe,
        [string]$InnerArgs,
        [string]$Name
    )
    Write-InstallLog "Extracting + installing: $Name"
    if (-not (Test-Path $ZipPath)) {
        Write-InstallLog "  Archive not found: $ZipPath" -Level 'FAIL'
        return $false
    }
    $extractDir = Join-Path $tempDir "zte_$Name"
    if (-not (Test-Path $extractDir)) {
        New-Item -ItemType Directory -Path $extractDir -Force | Out-Null
    }
    $proc = Start-Process $sevenZip -ArgumentList "x `"$ZipPath`" -o`"$extractDir`" -y" -Wait -PassThru
    if ($proc.ExitCode -ne 0) {
        Write-InstallLog "  $Name -- extraction failed (exit $($proc.ExitCode))" -Level 'FAIL'
        return $false
    }
    # Find the inner exe, searching recursively in case it is in a subdirectory
    $exePath = Join-Path $extractDir $InnerExe
    if (-not (Test-Path $exePath)) {
        $found = Get-ChildItem -Path $extractDir -Filter $InnerExe -Recurse -ErrorAction SilentlyContinue |
                 Select-Object -First 1
        if ($found) {
            $exePath = $found.FullName
        } else {
            Write-InstallLog "  $Name -- inner exe '$InnerExe' not found after extraction" -Level 'FAIL'
            return $false
        }
    }
    return (Invoke-Installer -FilePath $exePath -InstallArgs $InnerArgs -Name $Name)
}

# -- Main ----------------------------------------------------------------------

Write-InstallLog '==========================================='
Write-InstallLog ' Sandbox Toolkit -- In-Sandbox Installer    '
Write-InstallLog '==========================================='

# Load install manifest
if (-not (Test-Path $manifestPath)) {
    Write-InstallLog "Install manifest not found: $manifestPath" -Level 'FAIL'
    Write-InstallLog 'Run Start-Sandbox.ps1 on the host to regenerate, then relaunch the sandbox.' -Level 'WARN'
    Read-Host 'Press Enter to close'
    exit 1
}

try {
    $session = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
    Write-InstallLog "Profile: $($session.profile)  |  Generated: $($session.generated_at)"
} catch {
    Write-InstallLog "Failed to parse install manifest: $_" -Level 'FAIL'
    exit 1
}

# Copy all installers to writable temp -- hard-stop if this fails
try {
    Copy-SetupsToTemp
} catch {
    Write-InstallLog "Cannot copy installers: $_" -Level 'FAIL'
    Write-InstallLog 'Setup cannot continue. Check that Start-Sandbox.ps1 downloaded all files.' -Level 'WARN'
    Read-Host 'Press Enter to close'
    exit 1
}

$installed = 0
$failed    = 0
$manual    = 0

# Sort by install_order (manifest is pre-sorted, but be defensive)
$tools = $session.tools | Sort-Object install_order

foreach ($tool in $tools) {
    $src = Join-Path $tempDir $tool.filename
    Write-InstallLog "--- $($tool.display_name) ---"

    try {
        $ok = switch ($tool.installer_type) {
            'msi' {
                $installArgs = if ($tool.install_args) { $tool.install_args } else { '/qn /norestart' }
                Invoke-Installer -FilePath $src -InstallArgs $installArgs -Name $tool.display_name
            }
            'exe' {
                $installArgs = if ($tool.install_args) { $tool.install_args } else { '' }
                Invoke-Installer -FilePath $src -InstallArgs $installArgs -Name $tool.display_name
            }
            'zip' {
                $dest = if ($tool.extract_dest) { $tool.extract_dest } else { "%USERPROFILE%\Desktop\$($tool.id)" }
                Expand-ZipTool -ZipPath $src -Destination $dest -Name $tool.display_name
            }
            'zip_then_exe' {
                $innerArgs = if ($tool.inner_args) { $tool.inner_args } else { '' }
                Install-ZipThenExe -ZipPath $src -InnerExe $tool.inner_exe -InnerArgs $innerArgs -Name $tool.display_name
            }
            'manual' {
                Write-InstallLog "  MANUAL: $($tool.notes)" -Level 'WARN'
                if (Test-Path $src) {
                    Write-InstallLog "  Installer available at: $src" -Level 'WARN'
                } else {
                    Write-InstallLog '  No bundled installer file was staged for this tool.' -Level 'WARN'
                }
                $manual++
                $true   # Not a failure -- user must run it manually
            }
            default {
                Write-InstallLog "  Unknown installer_type '$($tool.installer_type)'" -Level 'WARN'
                $false
            }
        }
    } catch {
        Write-InstallLog "  Unexpected error installing $($tool.display_name): $_" -Level 'FAIL'
        $ok = $false
    }

    # Count manual tools separately so they don't inflate the success/fail counts
    if ($tool.installer_type -ne 'manual') {
        if ($ok) { $installed++ } else { $failed++ }
    }
}

# -- Summary -------------------------------------------------------------------

Write-InstallLog '==========================================='
Write-InstallLog "Done: $installed installed, $failed failed, $manual require manual steps."
if ($failed -gt 0) {
    Write-InstallLog 'See install-log.txt on the Desktop for details on failed items.' -Level 'WARN'
}
if ($manual -gt 0) {
    Write-InstallLog 'Manual tools: run their installers from %TEMP% when ready.' -Level 'WARN'
}
Write-InstallLog '==========================================='
